<?xml version="1.0"?>
<package format="3">
  <name>mini_dogu_fleet</name>
  <version>0.0.1</version>

  <description>
    Fleet monitoring and robot heartbeat management for Mini DOGU.
  </description>

  <maintainer email="your-email@example.com">
    Seongil Heo
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>mini_dogu_interfaces</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>