<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mini_dogu_mapping</name>
  <version>0.0.1</version>

  <description>
    Multi-robot SLAM, map-frame management, and mapping bringup for the Mini DOGU platform.
  </description>

  <maintainer email="seongil.e.heo@gmail.com">
    Seongil Heo
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>mini_dogu_description</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
